###
GET {{url}}receipts/13323af8-3cec-4a28-b249-e1af6ef79e51
Authorization: Bearer {{token}}

###
POST {{url}}receipts
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="receipt"; filename="file.jpg"
Content-Type: image/jpeg

< .\test.jpg

###