<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>V4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e3195e3f-3540-48ba-b43f-371a5e246594</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>

    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7"/>

    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.5.4"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.8.1"/>

    <PackageReference Include="MimeTypeMapOfficial" Version="1.0.17"/>

    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.0"/>

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5"/>

    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0"/>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Shared.fs"/>
    <Compile Include="Functions\ReceiptFunctions.fs"/>
    <Compile Include="Program.fs"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infra\Infra.fsproj"/>
    <ProjectReference Include="..\Parser.OpenAI\Parser.OpenAI.fsproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
