<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs"/>
    <Compile Include="Startup.fs"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="schema.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" Version="2.10.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
    <PackageReference Include="Azure.Identity" Version="1.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.fsproj"/>
  </ItemGroup>

</Project>
